[env:rx_node]
platform      = espressif32
board         = esp32dev
framework     = arduino

; Seri port hızı (pio monitor)
monitor_speed = 57600

; Kütüphaneler
lib_deps =
    https://github.com/mavlink/c_library_v2.git

; common/ klasörünü her iki proje de paylaşır
; RX node pin atamaları:
;   E22 UART : GPIO17(TX→E22 RXD), GPIO16(RX←E22 TXD)
;   E22 M0   : GPIO4
;   E22 M1   : GPIO2
;   E22 AUX  : GPIO15
build_flags =
    -I../common
    -DLORA_ESP_TX_PIN=17
    -DLORA_ESP_RX_PIN=16
    -DLORA_M0_PIN=4
    -DLORA_M1_PIN=2
    -DLORA_AUX_PIN=15

; Upload hızı
upload_speed  = 921600
