[env:tx_node]
platform      = espressif32
board         = esp32dev
framework     = arduino

; Seri port hızı (pio monitor)
monitor_speed = 115200

; Kütüphaneler
lib_deps =
    https://github.com/mavlink/c_library_v2.git

; common/ klasörünü her iki proje de paylaşır
build_flags =
    -I../common

; Upload hızı
upload_speed  = 921600
